version: "3.3"

services:
  database:
    image: postgres
    container_name: url_db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=url_database
      - POSTGRES_PASSWORD=admin
volumes:
  pgdata:
    driver: local